[package]
name = "mu2vid"
version = "0.1.0"
edition = "2024"
authors = ["michioxd <neko@michioxd.ch>"]

[dependencies]
anyhow = "1.0.102"
directories = "6.0.0"
env_logger = "0.11.10"
log = "0.4.30"
image = "0.25.10"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
wxdragon = "0.9.16"

[build-dependencies]
embed-manifest = "1.5.0"
